name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os || 'ubuntu' }}-latest
    continue-on-error: ${{ matrix.rust == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        rust:
          - nightly
          - beta
          - stable
          - 1.60 # MSRV
        include:
          - rust: stable
            os: macos
          - rust: nightly
            os: windows
    env:
      RUST_BACKTRACE: full

    steps:
    - uses: actions/checkout@v3

    - name: Install latest ${{ matrix.rust }}
      id: install-rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ matrix.rust }}
          override: true

    - name: setup cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-rustc-${{ steps.install-rust.outputs.rustc_hash }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: build
      run: |
        cargo build --verbose
        cargo test --verbose --no-run

    - name: run tests
      run: cargo test --verbose
