name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - nightly
          - beta
          - stable
          - 1.56.0 # MSRV
          
    env:
      RUST_BACKTRACE: full
      
    steps:
    - uses: actions/checkout@v3
    
    - name: update rust
      run: |
        rustup update stable
        cargo --version
    
    - name: Build
      run: |
        cargo build --verbose
        cargo test --verbose --no-run
        
    - name: Run tests
      run: cargo test --verbose
