name: deps

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

    - name: update rust
      run: |
        rustup update nightly
        cargo --version

    - name: setup cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: check outdated dependencies
      run: |
        cargo install --locked cargo-outdated || true
        cargo outdated --exit-code 1

    - name: check unused dependencies
      run: |
        cargo install --locked cargo-udeps || true
        cargo udeps
